# Generated by Django 4.1.7 on 2023-03-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
