# Generated by Django 4.1.7 on 2023-04-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_manufacturingprocess_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='op_number',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='app.manufacturingprocess'),
        ),
    ]
